#cloud-config
users:
  - default
  - name: root
    lock-passwd: false
    passwd: ${root_password}
  - name: ${username}
    ssh-authorized-keys:
      - ${photon_ssh_pub_key}
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    groups: sudo
    shell: /bin/bash
packages: ${encoded_packages}
${additional}

